---
# Production DNS Servers Inventory
# 
# Usage:
#   ansible-playbook -i inventories/production/hosts.yml site.yml
#
# To generate a new API key:
#   python3 -c "import secrets; print(secrets.token_urlsafe(32))"
#
# NOTE: Update the IP addresses and SSH settings for your environment

all:
  children:
    dns_servers:
      hosts:
        dns1:
          ansible_host: 172.25.62.243
          ansible_user: ubuntu
          
        dns2:
          ansible_host: 172.25.62.244
          ansible_user: ubuntu

        # Add more servers as needed:
        # dns3:
        #   ansible_host: 192.168.1.12
        #   ansible_user: ubuntu

  vars:
    # SSH settings
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
